#!/bin/bash

set -e

# base
SELF=$0
COMMAND_NAME=$(basename $SELF)

# docker settings
DOCKER_CONTAINER=""
DOCKER_NETWORK=""
DOCKER_TERM="bash"

# colors
SUCCESS='\033[0;32m'
WARNING='\033[0;33m'
ERROR='\033[0;31m'
OPTIONAL='\033[2;37m'
NC='\033[0m'

case $1 in
    on|start) # Start
        shift
        echo $BASE_DIR
        ;;
    
    off|stop) # Stop
        shift
        echo STOP
        ;;

    restart) # Restart
        shift
        $SELF stop
        $SELF start
        ;;

    build) # Build
        shift
        ;;

    destroy) # Destroy
        shift
        $SELF stop
        docker system prune --volumes --all
        ;;

    exec) # Execute command inside the main container
        shift
        docker exec -it $DOCKER_CONTAINER bash -c "$*"
        ;;

    attach) # Opens bash console inside the main container
        shift
        $SELF EXEC exec "${DOCKER_TERM}"
        ;;

    -h|--help) # Show help
        shift
        echo -e "\n${SUCCESS}${COMMAND_NAME}${NC} commands\n"
        AWK_FORMAT="${WARNING}%-20s${NC}${OPTIONAL}%-40s${NC}%s\n"
        AWK_SEPARATOR=") # "
        cat $0 |\
            # filter commands and their description
            awk -v format=$AWK_FORMAT -F"${AWK_SEPARATOR}" '{if ($2) printf format, $1, $3, $2}' |\
            # ignore last entry - help
            head -n-1
        ;;

    *)
        echo -e "${ERROR}Unknown command${NC}"
        echo -e "Use ${WARNING}${COMMAND_NAME} --help${NC} to get all available commands."
        exit 1
        ;;
esac
